[package]
name = "x509-util"
version = "0.1.0"
edition = "2021"

authors = ["Luke Cycon"]
license = "Apache-2.0 OR MIT"

[dependencies]
async-trait = "0.1.66"
bumpalo-herd = "0.1.2"
chrono = "0.4.24"
const-oid = { version = "0.9.2", features = ["db", "std"] }
der = "0.7.1"
flagset = "0.4.3"
lazy_static = "1.4.0"
pkcs1 = "0.7.1"
pkcs8 = { version = "0.10.1", features = ["pem"] }
rand = "0.8.5"
sha1 = "0.10.4"
spki = { version = "0.7.0", features = ["alloc", "pem", "std"] }
thiserror = "1.0.40"
x509-cert = { version = "0.1.1", features = ["alloc", "pem", "std"] }

[dev-dependencies]
p384 = "0.13.0"
rsa = "0.8.2"
sha2 = "0.10.5"
tokio = { version = "1.26.0", features = ["rt-multi-thread", "macros"] }
